In [23]:
# import libraries
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.cross_validation import train_test_split

/anaconda3/lib/python3.6/site-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [5]:
# Read the dataset
dataSet  = pd.read_csv("DataSet/app-store-apple-data-set-10k-apps/AppleStore.csv")

In [6]:
dataSet.head()

Unnamed: 0         id                                         track_name  \
0           1  281656475                                    PAC-MAN Premium   
1           2  281796108                          Evernote - stay organized   
2           3  281940292    WeatherBug - Local Weather, Radar, Maps, Alerts   
3           4  282614216  eBay: Best App to Buy, Sell, Save! Online Shop...   
4           5  282935706                                              Bible   

   size_bytes currency  price  rating_count_tot  rating_count_ver  \
0   100788224      USD   3.99             21292                26   
1   158578688      USD   0.00            161065                26   
2   100524032      USD   0.00            188583              2822   
3   128512000      USD   0.00            262241               649   
4    92774400      USD   0.00            985920              5320   

   user_rating  user_rating_ver     ver cont_rating   prime_genre  \
0          4.0              4.5   6.3.5          4+         Games   
1          4.0              3.5   8.2.2          4+  Productivity   
2          3.5              4.5   5.0.0          4+       Weather   
3          4.0              4.5  5.10.0         12+      Shopping   
4          4.5              5.0   7.5.1          4+     Reference   

   sup_devices.num  ipadSc_urls.num  lang.num  vpp_lic  
0               38                5        10        1  
1               37                5        23        1  
2               37                5         3        1  
3               37                5         9        1  
4               37                5        45        1

In [7]:
#  Drop the index and currency columns
dataSet.drop(labels=['Unnamed: 0', 'currency'], axis=1, inplace=True)

In [8]:
# Add the get_dummies columns to the originla Dataframe
dataSet = pd.concat([dataSet, pd.get_dummies(dataSet['prime_genre'], prefix_sep="genre", dummy_na=True)], axis = 1)

In [9]:
# Remove the '+' sign at the end of the rating values
dataSet['cont_rating']= [each.replace('+', '') for each in dataSet['cont_rating']]

# Typecasting  content Rating column to int type
dataSet['cont_rating'] = dataSet['cont_rating'].map(lambda x: int(x))

In [11]:
dataSet.dtypes

id                     int64
track_name            object
size_bytes             int64
price                float64
rating_count_tot       int64
rating_count_ver       int64
user_rating          float64
user_rating_ver      float64
ver                   object
cont_rating            int64
prime_genre           object
sup_devices.num        int64
ipadSc_urls.num        int64
lang.num               int64
vpp_lic                int64
Book                   uint8
Business               uint8
Catalogs               uint8
Education              uint8
Entertainment          uint8
Finance                uint8
Food & Drink           uint8
Games                  uint8
Health & Fitness       uint8
Lifestyle              uint8
Medical                uint8
Music                  uint8
Navigation             uint8
News                   uint8
Photo & Video          uint8
Productivity           uint8
Reference              uint8
Shopping               uint8
Social Networking      uint8
Sports        

In [60]:
X.dtypes

size_bytes            int64
price               float64
rating_count_tot      int64
rating_count_ver      int64
user_rating_ver     float64
cont_rating           int64
sup_devices.num       int64
ipadSc_urls.num       int64
lang.num              int64
dtype: object

In [70]:
# Building a Linear regression model for apps of games genre

gameDataset = dataSet[dataSet['Games'] == 1]
features = ['size_bytes','price','rating_count_tot','rating_count_ver','user_rating_ver', 'cont_rating','sup_devices.num','ipadSc_urls.num','lang.num']
X = gameDataset[features]
y = gameDataset['user_rating']

# print (X.shape, y.shape)


# # create training and testing vars
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

print (X_test.shape, y_test.shape)

lr = LinearRegression()
model= lr.fit(X_train, y_train)

(773, 9) (773,)


In [71]:
predictions = model.predict(X_test)
predictions[:5]

array([4.8777087 , 4.39986758, 3.62779277, 3.46679818, 1.04507705])

In [72]:
print ("Score for 'games' genre:", model.score(X_test, y_test))

Score: 0.7111622972461159


In [90]:
X.columns

Index(['size_bytes', 'price', 'rating_count_tot', 'rating_count_ver',
       'user_rating_ver', 'cont_rating', 'sup_devices.num', 'ipadSc_urls.num',
       'lang.num'],
      dtype='object')

In [94]:
pd.DataFrame({'variable': X.columns, 'coefficient': model.coef_}).sort_values(by='coefficient')

variable   coefficient
6   sup_devices.num -2.605372e-03
3  rating_count_ver -6.871185e-06
0        size_bytes -3.317968e-10
2  rating_count_tot  3.390762e-06
8          lang.num  3.477436e-03
5       cont_rating  3.486954e-03
1             price  5.433510e-03
7   ipadSc_urls.num  7.178417e-02
4   user_rating_ver  5.593559e-01

In [84]:
# Building a Linear regression model for apps of games Education

gameDataset = dataSet[dataSet['Education'] == 1]
features = ['size_bytes','price','rating_count_tot','rating_count_ver','user_rating_ver', 'cont_rating','sup_devices.num','ipadSc_urls.num','lang.num']
X = gameDataset[features]
y = gameDataset['user_rating']

# print (X.shape, y.shape)


# # create training and testing vars
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

print (X_test.shape, y_test.shape)

lr = LinearRegression()
EduModel= lr.fit(X_train, y_train)

(91, 9) (91,)


In [85]:
predictions = EduModel.predict(X_test)
predictions[:5]

array([4.16006242, 3.66844169, 3.72485163, 4.03924241, 4.25885857])

In [86]:
print ("Score for 'Education genre':", EduModel.score(X_test, y_test))

Score for 'Education genre': 0.46106297905135435


In [87]:
EduModel.coef_

array([ 5.98571703e-11,  4.10649669e-03,  4.14279129e-06, -7.50442095e-06,
        5.75298362e-01, -1.48995077e-03,  2.13403419e-03,  7.20910197e-02,
        2.77815494e-03])

In [ ]:
#def df_of_coefs(model, feature_names):

In [ ]:
pd.DataFrame({'variable': X.columns, 'coefficient': EduModel.coef_}).sort_values(by='coefficient')

In [95]:
pd.DataFrame({'variable': X.columns, 'coefficient': EduModel.coef_}).sort_values(by='coefficient')

variable   coefficient
5       cont_rating -1.489951e-03
3  rating_count_ver -7.504421e-06
0        size_bytes  5.985717e-11
2  rating_count_tot  4.142791e-06
6   sup_devices.num  2.134034e-03
8          lang.num  2.778155e-03
1             price  4.106497e-03
7   ipadSc_urls.num  7.209102e-02
4   user_rating_ver  5.752984e-01